gentrace/gentrace-node

.npmrc
examples/playground-movies/README.md
package.json

this change allows for future `pnpm` versions to be used without an unexpected build error. 
should be an overall plus, since `pnpm` releases are rather frequent e.g. https://github.com/pnpm/pnpm/releases

build: upgrade to pnpm v9.0.6, and make versioning more flexible

---

.github/workflows/release-please.yaml

remove "--frozen-lockfile" to increase flexibility as "pnpm" versions change

update GitHub release workflow to support newer pnpm

---

packages/core/providers/utils.ts

example of a more informative error message is "Pipeline not found" (instead of "Request failed with status code 400")

fix: show more informative error message if available

---

.changeset/bright-cougars-crash.md
pnpm-lock.yaml

* The express dependency is not in `core` so needed to regenerate lock file

fix: update lock file for core dependencies

---

.changeset/bright-rivers-remember.md
examples/evaluation/src/test-job-runner-webhook.ts
examples/evaluation/src/test-job-runner.ts
packages/core/providers/test-job-runner.ts

* Add a `variables` optional property to prompt parameter type
* Question: Is this duplicative with the `inputType` that is provided for validation? Is there a more concise way of doing this?
Errors if types don't align:
Depends on: https://github.com/gentrace/gentrace/pull/3821
Fixes: GT-1121

feat: add variables to prompt parameters

---

.changeset/eight-jobs-lie.md
packages/evals/src/llm-evaluator.ts

* Pass in provided image URLs to llm evals so they can be used in the evaluation
Example:

feat: provide image urls for llm evals

---

examples/evaluation/src/evaluation-list.ts
packages/core/providers/init.ts

Fix issue where the TypeScript compiler was removing the full logic of the `getEvaluations()` function.

feat(core): add basePath and update error messages

---

README.md

Modify the README to reflect using `npm install` and also update dependencies for OpenTelemetry packages to make them compatible.

fix: Update package manager instructions in README

---

src/lib/index.ts

I forgot to actually export the traced function such that it'll be available inside of the default exports from the main package.

feat: Add traced export in lib/index.ts

---

README.md
examples/openai-composition.ts
examples/test-openai-composition.ts
package.json
src/lib/index.ts
src/lib/interaction.ts
yarn.lock

We're introducing OTLP baggage to interactions to make sure that every span underneath an interaction has `gentrace.sample`. 
This does require users to provide a `BaggageSpanProcessor` to apply the baggage attributes to the span. I've included an example in `openai-composition.ts` to show how this is done.
**Remaining items**

fix: Add `Baggage` to the interaction to `gentrace.sample`

---

README.md
examples/eval-dataset.ts
examples/eval-once.ts
examples/no-params.ts
examples/openai-composition.ts
examples/test-openai-composition.ts
src/lib/eval-dataset.ts
src/lib/eval-once.ts
src/lib/index.ts
tests/lib/eval-dataset.test.ts
tests/lib/eval-once.test.ts

Renamed test functions to eval functions to better reflect their purpose in evaluating AI systems. Makes the interface similar to Python.
- Renamed `test` to `evalOnce` for single evaluations
- Renamed `testDataset` to `evalDataset` for dataset-based evaluations
- Updated all imports, function calls, and documentation to reflect these changes
- Renamed related files:
- `test-single.ts` → `eval-once.ts`
- `test-dataset.ts` → `eval-dataset.ts`
- `test-dataset.test.ts` → `eval-dataset.test.ts`
- `test-single.test.ts` → `eval-once.test.ts`
- Updated example files to use the new function names
- Updated README.md to reflect the new terminology
1. Run the updated examples to verify they work with the new function names:
```
GENTRACE_PIPELINE_ID=<your-pipeline-id> GENTRACE_API_KEY=<your-api-key> …
```

chore: Rename to evalOnce() and evalDataset()

---

src/lib/eval-dataset.ts
src/lib/eval-once.ts
tests/lib/eval-dataset.test.ts
tests/lib/eval-once.test.ts

Removed redundant `gentrace.test_case_name` span attribute
- Removed the automatic setting of `gentrace.test_case_name` span attribute in `eval-once.ts` and `eval-dataset.ts`
- Made the `spanAttributes` parameter optional in `RunEvalInternalOptions` interface
- Updated the `_runEval` function to handle potentially undefined `spanAttributes`
- Updated all relevant tests to reflect these changes
1. Run the existing test suite to ensure all tests pass
2. Verify that test spans are still created correctly but without the redundant `gentrace.test_case_name` attribute
3. Confirm that test cases with explicit IDs still have the `gentrace.test_case_id` attribute set
This change streamlines the telemetry data by removing redundant span attributes. The `gentrace.test_case_name` attribute was …

chore: Remove test_case_name attribute

---

src/lib/eval-dataset.ts
src/lib/eval-once.ts
src/lib/interaction.ts
src/lib/otel/constants.ts
src/lib/otel/index.ts
src/lib/otel/sampler.ts
src/lib/otel/span-processor.ts
src/lib/traced.ts
tests/lib/eval-dataset.test.ts
tests/lib/eval-once.test.ts
tests/lib/interaction.test.ts
tests/lib/traced.test.ts

Refactored OpenTelemetry attribute keys into constants for better maintainability and consistency.
- Created and consolidated OpenTelemetry attribute keys as named constants in `src/lib/otel/constants.ts`
- Renamed `GENTRACE_SAMPLE_KEY` to `ATTR_GENTRACE_SAMPLE` for consistency
- Added new constants for various Gentrace attributes:
- `ATTR_GENTRACE_PIPELINE_ID`
- `ATTR_GENTRACE_TEST_CASE_ID`
- `ATTR_GENTRACE_EXPERIMENT_ID`
- `ATTR_GENTRACE_FN_ARGS`
- `ATTR_GENTRACE_FN_OUTPUT`
- Updated all references to hardcoded string literals throughout the codebase to use these constants
- Updated tests to use the new constants
1. Run the existing test suite to ensure all functionality works as expected
2. Verify that tracing still works correctly in applications using the library
3. Check that spans …

fix: Refactor attributes into constants

---

.github/workflows/claude-code.yml
README.md
examples/eval-dataset.ts
examples/functions/composition.ts
examples/no-params.ts
examples/openai-composition.ts
examples/test-openai-composition.ts
src/lib/constants.ts
src/lib/index.ts
src/lib/interaction.ts
src/lib/traced.ts
tests/lib/interaction.test.ts
tests/lib/traced.test.ts

Made interaction names explicit by requiring a name parameter in the `interaction()` options bag.
- Modified the `interaction()` function to require an explicit `name` parameter instead of using function names or a default "anonymous" value
- Removed the `ANONYMOUS_SPAN_NAME` constant and related fallback logic
- Updated all example files to include explicit names for interactions
- Updated the `traced()` function to require a name parameter rather than inferring it
- Updated all tests to accommodate the new required name parameter
1. Run the updated examples to verify they work with the new explicit naming:
```
ts-node examples/no-params.ts
ts-node examples/openai-composition.ts
ts-node examples/test-dataset.ts
ts-node examples/test-openai-composition.ts
```
2. Run the test suite to …

chore: Add interaction name for simplicity

---

.gitignore
README.md

Added documentation for the new `traced` decorator function to the SDK for more granular tracing capabilities and updated documentation.
- Added `.venv` to the `.gitignore` file
- Updated the README to introduce the new `traced` decorator function alongside the existing `interaction` function
- Added a comprehensive code example demonstrating how to use the `traced` decorator for lower-level tracing
- Updated the warning note to include `traced` in the list of instrumentation features that require OpenTelemetry
1. Use the `traced` decorator to wrap specific functions in your codebase:
```typescript
const summarizeUser = traced('OpenAI Call', async (userInfo: string) => {
// Function implementation
});
```
2. Combine with `interaction` for hierarchical tracing as shown in the new example …

chore: Detail `traced()` in the docs

---

src/lib/utils.ts

Updated the OpenTelemetry trace exporter URL to use the new endpoint format.
Changed the URL for the OpenTelemetry trace exporter from `https://api.gentrace.ai/v1/otel/traces` to `https://gentrace.ai/api/v1/otel/traces`.
1. Ensure the Gentrace API key is set in the environment variables
2. Run a trace export operation
3. Verify that traces are being properly sent to the new endpoint
4. Check that no errors are occurring during the export process
The Gentrace API endpoint structure has been updated, requiring clients to use the new URL format. This change ensures compatibility with the current API infrastructure.

fix: Update OTLPTraceExporter URL

---

examples/openai-ai-sdk-responses.ts
examples/openai-responses-api.ts

Add in examples for the OpenAI Responses API, including how to use it with GenAI Semantic conventions and also with the AI SDK.

feat: Add OpenAI AI SDK and Responses API examples

---

examples/evaluation-dataset.ts
src/lib/experiment-control.ts
src/lib/experiment.ts
src/lib/interaction.ts
tests/lib/experiment-control.test.ts
tests/lib/experiment.test.ts
tests/mocks/handlers.ts

**Key changes:**
- Make sure that `experiment()` returns the experiment object. The return value of experiment callback doesn't really matter.
- Augment the experiment object with the full URL constructed using the base URL

feat(experiment): return experiment object metadata from `experiment()` invocation

---

README.md
examples/evaluation-dataset.ts
examples/evaluation.ts
src/lib/experiment.ts
tests/lib/experiment.test.ts

This PR is designed to make sure that the pipeline ID is moved into the options object in the second parameter, and also by default, if the pipeline ID is excluded, it passes a default identifier—which will automatically resolve to the default pipeline for that particular organization specified by the API key.

feat(experiment): support options-based pipelineId

---

examples/custom-configuration.ts
examples/genai-semantic-conventions.ts
src/lib/otel/diag-logger.ts
src/lib/otel/setup.ts
src/lib/otel/types.ts
src/lib/otel/utils.ts
src/lib/warnings.ts
tests/lib/init-warnings.test.ts

- Show errors for partial ingestion
- Unify the warning system
- Use `logLevel` and `logger` parameters for Stainless to inform how OTEL logger and our own boxed errors and warnings are emitted.

fix: add an error for partial ingestion, unify logging with Stainless' logging system

---

src/lib/eval-once.ts
src/lib/otel/constants.ts
src/lib/otel/span-processor.ts

Added support for tracking whether spans are part of an experiment with a new baggage attribute.
- Added a new constant `ATTR_GENTRACE_IN_EXPERIMENT` to track when spans are part of an experiment
- Modified the `_runEval` function to set this new attribute in the baggage
- Updated the `GentraceSpanProcessor` to propagate both sampling and experiment attributes from baggage to spans
- Created a `gentraceBaggageKeys` array to maintain the list of baggage keys that should be propagated to spans
1. Run an experiment using the SDK
2. Verify that spans created during the experiment have both the `gentrace.sample` and `gentrace.in_experiment` attributes set to "true"
3. Check that these attributes are properly propagated through the span hierarchy
This change enables better tracking of spans …

feat: add gentrace.in_experiment baggage key
